### ISSUE TITLE
Change bulleted text to black

### ISSUE THREAD

**Issue by ericronne** [18F/cloud-marketplaceholder#18]
Ideally the bullets would be $medium-gray and the accompanying text $black.
Could be tricky. If so, we can make everything black.

**Comment by tram** [comment]
Hmmm… I don't see a $medium-gray. :-/ There's $dark-gray: #374b54 or we could define a color.

**Comment by ericronne** [comment]
I defined one on the style2 branch, here 'tis …
$medium-gray: #55666D;
thx
