### ISSUE TITLE
One-pager formatting things

### ISSUE THREAD

**Issue by ericronne** [18F/cloud-marketplaceholder#7]
- [x] Bullets
![image](https://user-images.githubusercontent.com/9259185/29832242-2ba5ff3e-8cad-11e7-91f6-ef688250dbab.png)

 - [x] Overall width (too wide)
![image](https://user-images.githubusercontent.com/9259185/29832264-3ef05292-8cad-11e7-8325-269e9fd6dcf6.png)

 - [x] Link / Subhead format is funky
![image](https://user-images.githubusercontent.com/9259185/29832282-4e96d734-8cad-11e7-860c-d00f01af0bb7.png)

**Comment by tram** [comment]
Okay, so, here's my swing at this. Overriding these rules in uswds.css…

ul li { display: table-row; }
ul, ol { list-style: none; padding-left: 0; display: table; }

…with these in main (or somewhere)…

ul li { display: list-item; }
ul, ol { list-style: disc; padding-left: 2em; display: table;}

…should do it.

**Comment by ericronne** [comment]
onnit.

**Comment by ericronne** [comment]
a couple niggling remainders, but can cover in another issue
